### ISSUE TITLE
Does voie support named views?

### ISSUE THREAD

**Issue by zhongqf** [inca/voie#2]
Something like `<v-view name="header"><v-view>`. `vue-router` does not support it.

**Comment by inca** [comment]
Currently, no. This would require to maintain several views per state, akin to [ui-router's multiple named views](https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views) — this feature is [known to be a source of many problems](https://github.com/angular-ui/ui-router/search?q=named+view&type=Issues&utf8=%E2%9C%93) (and I personally believe that it's there only because Angular, as opposed to Vue, does not contain a clean component model).

Now in practice there are only two use-cases for multiple named views:

  1. you have a "main" view (state) and a **single** "place" which can render different subviews — in this case it is possible to map these subviews to URL (because the place in single) — therefore, you can just use child states

  2. you have **more than one** "places", each can render a different component — in this case you obviously can't map all of them to a single URL, and most likely you just want to factor out a component (for reusability or just to keep things clean) — so you can simply use Vue component system for that.

**Comment by zhongqf** [comment]
Thanks a lot for comment.
OK, change my question. :smile: 

Is there any alternative solutions? Like a customized property defined in state definition?


    app.add('user.dashboard', {
        header: headerComponent,
        title: titleComponent,
        component: {
            template: "<component :is='currentState.header'></component><h1>Hello, {{ user.name }}!</h1>"
        }
    });

Sorry I can not find this usage in your document and have not checked the source.

**Comment by zhongqf** [comment]
OK, Thanks!
